# This file is part of the jupeter/s3-behat package.
# (c) Paweł Jędrzejewski
# (c) Piotr Plenik

default:
    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: false

    extensions:
        Lakion\Behat\MinkDebugExtension:
            directory: etc/build
            clean_start: false
            screenshot: true

        Behat\MinkExtension:
            files_path: "%paths.base%/src/Sylius/Behat/Resources/fixtures/"
            base_url: "http://localhost:8080/"
            default_session: symfony
            javascript_session: chrome
            sessions:
                symfony:
                    symfony: ~
                chrome:
                    selenium2:
                        browser: chrome
                        capabilities:
                            browserName: chrome
                            browser: chrome
                            version: ""
                            chrome:
                                switches:
                                    - "start-fullscreen"
                                    - "start-maximized"
                                    - "no-sandbox"
                firefox:
                    selenium2:
                        browser: firefox
            show_auto: false

        FriendsOfBehat\SymfonyExtension:
            kernel:
                class: TestAppKernel
                path: vendor/jupeter/s3-behat/src/TestAppKernel.php

        FriendsOfBehat\CrossContainerExtension: ~

        FriendsOfBehat\PerformanceExtension: ~

        FriendsOfBehat\VariadicExtension: ~

    gherkin:
        filters:
            tags: "~@todo && ~@cli" # CLI is excluded as it registers an error handler that mutes fatal errors